name: MapLockPlus
version: ${project.version}
main: org.FreeZeeZon.maplockplus.MapLockPlus
api-version: '1.21'
authors: [ FreeZeeZon ]
description: Plugin for locking maps from being copied

commands:
  maplock:
    description: Lock or unlock a map
    usage: /<command> <lock|unlock|anon|reload>
    aliases: [ml, lockmap]

permissions:
  maplock.use:
    description: Allows locking and unlocking maps
    default: true
  maplock.reload:
    description: Allows reloading the plugin config
    default: op
  maplock.admin:
    description: Grants capability to unlock ANY map (ignoring owner)
    default: op
  maplock.*:
    description: Grants all MapLock plugin permissions
    default: op
    children:
      maplock.use: true
      maplock.reload: true
      maplock.admin: true